/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  FavoriteCarPark as PrismaFavoriteCarPark,
  CarPark as PrismaCarPark,
  User as PrismaUser,
} from "@prisma/client";

export class FavoriteCarParkServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.FavoriteCarParkCountArgs, "select">
  ): Promise<number> {
    return this.prisma.favoriteCarPark.count(args);
  }

  async favoriteCarParks(
    args: Prisma.FavoriteCarParkFindManyArgs
  ): Promise<PrismaFavoriteCarPark[]> {
    return this.prisma.favoriteCarPark.findMany(args);
  }
  async favoriteCarPark(
    args: Prisma.FavoriteCarParkFindUniqueArgs
  ): Promise<PrismaFavoriteCarPark | null> {
    return this.prisma.favoriteCarPark.findUnique(args);
  }
  async createFavoriteCarPark(
    args: Prisma.FavoriteCarParkCreateArgs
  ): Promise<PrismaFavoriteCarPark> {
    return this.prisma.favoriteCarPark.create(args);
  }
  async updateFavoriteCarPark(
    args: Prisma.FavoriteCarParkUpdateArgs
  ): Promise<PrismaFavoriteCarPark> {
    return this.prisma.favoriteCarPark.update(args);
  }
  async deleteFavoriteCarPark(
    args: Prisma.FavoriteCarParkDeleteArgs
  ): Promise<PrismaFavoriteCarPark> {
    return this.prisma.favoriteCarPark.delete(args);
  }

  async getCarPark(parentId: string): Promise<PrismaCarPark | null> {
    return this.prisma.favoriteCarPark
      .findUnique({
        where: { id: parentId },
      })
      .carPark();
  }

  async getUser(parentId: string): Promise<PrismaUser | null> {
    return this.prisma.favoriteCarPark
      .findUnique({
        where: { id: parentId },
      })
      .user();
  }
}
