/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CarPark } from "./CarPark";
import { CarParkCountArgs } from "./CarParkCountArgs";
import { CarParkFindManyArgs } from "./CarParkFindManyArgs";
import { CarParkFindUniqueArgs } from "./CarParkFindUniqueArgs";
import { CreateCarParkArgs } from "./CreateCarParkArgs";
import { UpdateCarParkArgs } from "./UpdateCarParkArgs";
import { DeleteCarParkArgs } from "./DeleteCarParkArgs";
import { FavoriteCarParkFindManyArgs } from "../../favoriteCarPark/base/FavoriteCarParkFindManyArgs";
import { FavoriteCarPark } from "../../favoriteCarPark/base/FavoriteCarPark";
import { CarParkService } from "../carPark.service";
@graphql.Resolver(() => CarPark)
export class CarParkResolverBase {
  constructor(protected readonly service: CarParkService) {}

  async _carParksMeta(
    @graphql.Args() args: CarParkCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [CarPark])
  async carParks(
    @graphql.Args() args: CarParkFindManyArgs
  ): Promise<CarPark[]> {
    return this.service.carParks(args);
  }

  @graphql.Query(() => CarPark, { nullable: true })
  async carPark(
    @graphql.Args() args: CarParkFindUniqueArgs
  ): Promise<CarPark | null> {
    const result = await this.service.carPark(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => CarPark)
  async createCarPark(
    @graphql.Args() args: CreateCarParkArgs
  ): Promise<CarPark> {
    return await this.service.createCarPark({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => CarPark)
  async updateCarPark(
    @graphql.Args() args: UpdateCarParkArgs
  ): Promise<CarPark | null> {
    try {
      return await this.service.updateCarPark({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => CarPark)
  async deleteCarPark(
    @graphql.Args() args: DeleteCarParkArgs
  ): Promise<CarPark | null> {
    try {
      return await this.service.deleteCarPark(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [FavoriteCarPark], { name: "favoriteCarParks" })
  async findFavoriteCarParks(
    @graphql.Parent() parent: CarPark,
    @graphql.Args() args: FavoriteCarParkFindManyArgs
  ): Promise<FavoriteCarPark[]> {
    const results = await this.service.findFavoriteCarParks(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
